### PR TITLE
ui: multi-language support for Workspacee Types page and its subpages

### PR DESCRIPTION
**Pull request by ghost**
iShot_2022-08-04_21 14 52
iShot_2022-08-04_21 15 25
iShot_2022-08-04_21 15 29
iShot_2022-08-04_21 15 34
iShot_2022-08-04_21 16 35
iShot_2022-08-04_21 16 52
iShot_2022-08-04_21 17 27
iShot_2022-08-04_21 37 04
iShot_2022-08-04_21 37 58
iShot_2022-08-04_21 38 11
iShot_2022-08-04_21 38 42

### CODE REVIEW

**Review by dengmingtong — DISMISSED** [review]

**Comment by luorobin-a2z** [comment]
image
--> ”目前可用的工作区类型“

**Comment by luorobin-a2z** [comment]
image
--> 目前暂无任何已导入和工作区类型

**Comment by luorobin-a2z** [comment]
所有”环境类型“ --> 都改成 ”工作区类型“
image
image
image
image

**Comment by ghost** [comment]
Adopted robin's suggestion in [the latest update](https://github.com/awslabs/service-workbench-on-aws-cn/pull/72/commits/7eedbebdc0b8d995338a116fab1f98485507595a)

**Comment by dengmingtong** [comment]
Please resolve all conversations.

**Comment by ghost** [comment]
> Please resolve all conversations.

All the conversations have been dealt with long ago, please take a look at the above on this page

**Review by zxkane — APPROVED** [review]

**Pull request merged**
